//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using Entidades;

    public partial class RestauranteEntities : DbContext
    {
        public RestauranteEntities()
            : base("name=RestauranteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Mesa> Mesa { get; set; }
        public virtual DbSet<Reservaciones> Reservaciones { get; set; }
    
        public virtual int SP_ActualizarCliente(Nullable<int> id_cliente, string nombre, string apellidos, string telefono, string correo_Electronico)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidosParameter = apellidos != null ?
                new ObjectParameter("Apellidos", apellidos) :
                new ObjectParameter("Apellidos", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var correo_ElectronicoParameter = correo_Electronico != null ?
                new ObjectParameter("Correo_Electronico", correo_Electronico) :
                new ObjectParameter("Correo_Electronico", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ActualizarCliente", id_clienteParameter, nombreParameter, apellidosParameter, telefonoParameter, correo_ElectronicoParameter);
        }
    
        public virtual int SP_ActualizarMenu(Nullable<int> id_menu, Nullable<decimal> precio, string descripcion)
        {
            var id_menuParameter = id_menu.HasValue ?
                new ObjectParameter("id_menu", id_menu) :
                new ObjectParameter("id_menu", typeof(int));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(decimal));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ActualizarMenu", id_menuParameter, precioParameter, descripcionParameter);
        }
    
        public virtual int SP_ActualizarMesa(Nullable<int> id_mesa, Nullable<int> numero_Mesa, string descripcion)
        {
            var id_mesaParameter = id_mesa.HasValue ?
                new ObjectParameter("id_mesa", id_mesa) :
                new ObjectParameter("id_mesa", typeof(int));
    
            var numero_MesaParameter = numero_Mesa.HasValue ?
                new ObjectParameter("Numero_Mesa", numero_Mesa) :
                new ObjectParameter("Numero_Mesa", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ActualizarMesa", id_mesaParameter, numero_MesaParameter, descripcionParameter);
        }
    
        public virtual int SP_ActualizarReservacion(Nullable<int> id_reservacion, Nullable<int> iD_cliente, Nullable<int> iD_mesa, Nullable<int> iD_menu, Nullable<int> cantidad, Nullable<System.DateTime> fecha_reservacion)
        {
            var id_reservacionParameter = id_reservacion.HasValue ?
                new ObjectParameter("id_reservacion", id_reservacion) :
                new ObjectParameter("id_reservacion", typeof(int));
    
            var iD_clienteParameter = iD_cliente.HasValue ?
                new ObjectParameter("ID_cliente", iD_cliente) :
                new ObjectParameter("ID_cliente", typeof(int));
    
            var iD_mesaParameter = iD_mesa.HasValue ?
                new ObjectParameter("ID_mesa", iD_mesa) :
                new ObjectParameter("ID_mesa", typeof(int));
    
            var iD_menuParameter = iD_menu.HasValue ?
                new ObjectParameter("ID_menu", iD_menu) :
                new ObjectParameter("ID_menu", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(int));
    
            var fecha_reservacionParameter = fecha_reservacion.HasValue ?
                new ObjectParameter("Fecha_reservacion", fecha_reservacion) :
                new ObjectParameter("Fecha_reservacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ActualizarReservacion", id_reservacionParameter, iD_clienteParameter, iD_mesaParameter, iD_menuParameter, cantidadParameter, fecha_reservacionParameter);
        }
    
        public virtual ObjectResult<SP_ConsCliente_Result> SP_ConsCliente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsCliente_Result>("SP_ConsCliente");
        }
    
        public virtual ObjectResult<SP_ConsClienteXID_Result> SP_ConsClienteXID(Nullable<int> id_Cliente)
        {
            var id_ClienteParameter = id_Cliente.HasValue ?
                new ObjectParameter("id_Cliente", id_Cliente) :
                new ObjectParameter("id_Cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsClienteXID_Result>("SP_ConsClienteXID", id_ClienteParameter);
        }
    
        public virtual ObjectResult<SP_ConsMenu_Result> SP_ConsMenu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsMenu_Result>("SP_ConsMenu");
        }
    
        public virtual ObjectResult<SP_ConsMenuXID_Result> SP_ConsMenuXID(Nullable<int> id_menu)
        {
            var id_menuParameter = id_menu.HasValue ?
                new ObjectParameter("id_menu", id_menu) :
                new ObjectParameter("id_menu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsMenuXID_Result>("SP_ConsMenuXID", id_menuParameter);
        }
    
        public virtual ObjectResult<SP_ConsMesa_Result> SP_ConsMesa()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsMesa_Result>("SP_ConsMesa");
        }
    
        public virtual ObjectResult<SP_ConsMesaXID_Result> SP_ConsMesaXID(Nullable<int> id_mesa)
        {
            var id_mesaParameter = id_mesa.HasValue ?
                new ObjectParameter("id_mesa", id_mesa) :
                new ObjectParameter("id_mesa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsMesaXID_Result>("SP_ConsMesaXID", id_mesaParameter);
        }
    
        public virtual ObjectResult<SP_ConsReservacion_Result> SP_ConsReservacion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsReservacion_Result>("SP_ConsReservacion");
        }
    
        public virtual ObjectResult<SP_ConsReservacionXID_Result> SP_ConsReservacionXID(Nullable<int> id_reservacion)
        {
            var id_reservacionParameter = id_reservacion.HasValue ?
                new ObjectParameter("id_reservacion", id_reservacion) :
                new ObjectParameter("id_reservacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsReservacionXID_Result>("SP_ConsReservacionXID", id_reservacionParameter);
        }
    
        public virtual int SP_EliminarCliente(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EliminarCliente", id_clienteParameter);
        }
    
        public virtual int SP_EliminarMenu(Nullable<int> id_menu)
        {
            var id_menuParameter = id_menu.HasValue ?
                new ObjectParameter("id_menu", id_menu) :
                new ObjectParameter("id_menu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EliminarMenu", id_menuParameter);
        }
    
        public virtual int SP_EliminarMesa(Nullable<int> id_mesa)
        {
            var id_mesaParameter = id_mesa.HasValue ?
                new ObjectParameter("id_mesa", id_mesa) :
                new ObjectParameter("id_mesa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EliminarMesa", id_mesaParameter);
        }
    
        public virtual int SP_EliminarReservacion(Nullable<int> id_reservacion)
        {
            var id_reservacionParameter = id_reservacion.HasValue ?
                new ObjectParameter("id_reservacion", id_reservacion) :
                new ObjectParameter("id_reservacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EliminarReservacion", id_reservacionParameter);
        }
    
        public virtual int sp_InsertarCliente(string nombre, string apellidos, string telefono, string correo_Electronico)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidosParameter = apellidos != null ?
                new ObjectParameter("Apellidos", apellidos) :
                new ObjectParameter("Apellidos", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var correo_ElectronicoParameter = correo_Electronico != null ?
                new ObjectParameter("Correo_Electronico", correo_Electronico) :
                new ObjectParameter("Correo_Electronico", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertarCliente", nombreParameter, apellidosParameter, telefonoParameter, correo_ElectronicoParameter);
        }
    
        public virtual int SP_InsertarMenu(Nullable<decimal> precio, string descripcion)
        {
            var precioParameter = precio.HasValue ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(decimal));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsertarMenu", precioParameter, descripcionParameter);
        }
    
        public virtual int SP_InsertarMesa(Nullable<int> numero_Mesa, string descripcion)
        {
            var numero_MesaParameter = numero_Mesa.HasValue ?
                new ObjectParameter("Numero_Mesa", numero_Mesa) :
                new ObjectParameter("Numero_Mesa", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsertarMesa", numero_MesaParameter, descripcionParameter);
        }
    
        public virtual int SP_InsertarReservacion(Nullable<int> iD_cliente, Nullable<int> iD_mesa, Nullable<int> iD_menu, Nullable<int> cantidad, Nullable<System.DateTime> fecha_reservacion)
        {
            var iD_clienteParameter = iD_cliente.HasValue ?
                new ObjectParameter("ID_cliente", iD_cliente) :
                new ObjectParameter("ID_cliente", typeof(int));
    
            var iD_mesaParameter = iD_mesa.HasValue ?
                new ObjectParameter("ID_mesa", iD_mesa) :
                new ObjectParameter("ID_mesa", typeof(int));
    
            var iD_menuParameter = iD_menu.HasValue ?
                new ObjectParameter("ID_menu", iD_menu) :
                new ObjectParameter("ID_menu", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(int));
    
            var fecha_reservacionParameter = fecha_reservacion.HasValue ?
                new ObjectParameter("Fecha_reservacion", fecha_reservacion) :
                new ObjectParameter("Fecha_reservacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsertarReservacion", iD_clienteParameter, iD_mesaParameter, iD_menuParameter, cantidadParameter, fecha_reservacionParameter);
        }
    }
}
